create table role (id bigint generated by default as identity,role varchar(255) not null,primary key (id));
create table user (id bigint generated by default as identity,email varchar_ignorecase(255),firstName varchar(255),lastName varchar(255),password varchar(255),primary key (id));
create table user_role (user_id bigint not null,roles_id bigint not null);
alter table role add constraint UK_bjxn5ii7v7ygwx39et0wawu0q  unique (role);
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe  unique (email);
alter table user_role add constraint FK_5k3dviices5fr7560hvc81x4r foreign key (roles_id) references role;
alter table user_role add constraint FK_apcc8lxk2xnug8377fatvbn04 foreign key (user_id) references user;
